
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'

export enum UnderlyingType {
  NATIVE = "NATIVE", VIRTUAL_SINGLE = "VIRTUAL_SINGLE", VIRTUAL_FIRST_ASSET = "VIRTUAL_FIRST_ASSET"
}




@Entity("Pool")
export class Pool extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	chain_id: Int

	@Required
	@Column("Int")
	timestamp: Int

	@Required
	@Column("Int")
	creation_block_number: Int

	@Required
	@Column("String")
	underlying_token_address: String

	@Required
	@Column("Int")
	underlying_token_index: Int

	@Required
	@Column("String")
	underlying_token_symbol: String

	@Required
	@Column("Int")
	underlying_token_decimals: Int

	@Required
	@Column("String")
	receipt_token_address: String

	@Required
	@Column("String")
	receipt_token_symbol: String

	@Required
	@Column("Int")
	receipt_token_decimals: Int

	@Required
	@Column("String")
	pool_address: String

	@Required
	@Column("String")
	pool_symbol: String

	@Required
	@Column("String")
	underlying_type: UnderlyingType

	@Required
	@Column("String")
	strategy: String

	@Required
	@Column("Float")
	earned: Float

	@Required
	@Column("Float")
	earnedSnapshot: Float
  constructor(data: Partial<Pool>) {super()}
}

@Entity("Strategy")
export class Strategy extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	vault: String
  constructor(data: Partial<Strategy>) {super()}
}

@Entity("VaultUser")
export class VaultUser extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	account: String

	@Required
	@Column("String")
	vault: String

	@Required
	@Column("Float")
	underlying_token_amount: Float

	@Required
	@Column("Float")
	underlying_token_amount_usd: Float

	@Required
	@Column("Float")
	earned: Float

	@Required
	@Column("Float")
	earnedSnapshot: Float
  constructor(data: Partial<VaultUser>) {super()}
}


const source = `enum UnderlyingType {
    # real underlying that strategy use (LP token, ALM token, asset)
    NATIVE
    # single asset of strategy we use as underlying here
    VIRTUAL_SINGLE
    # the first of final strategy assets we use as underlying here
    VIRTUAL_FIRST_ASSET
}


# Output column headers must match the following : chain_id, timestamp, creation_block_number, underlying_token_address, underlying_token_index, underlying_token_symbol, underlying_token_decimals, receipt_token_address, receipt_token_symbol, receipt_token_decimals, pool_address, pool_symbol

type Pool @entity {
    id: ID!

    # Schema fields
    chain_id: Int!
    timestamp: Int!
    creation_block_number: Int!
    underlying_token_address: String!
    underlying_token_index: Int!
    underlying_token_symbol: String!
    underlying_token_decimals: Int!
    receipt_token_address: String!
    receipt_token_symbol: String!
    receipt_token_decimals: Int!
    pool_address: String!
    pool_symbol: String!

    # helper fields
    underlying_type: UnderlyingType!
    strategy: String!
    earned: Float!
    earnedSnapshot: Float!
}

type Strategy @entity {
    id: ID!

    vault: String!
}

type VaultUser @entity {
    "{user_address}-{vault_address}"
    id: ID!
    "{user_address}"
    account: String!
    "{vault_address}"
    vault: String!

    underlying_token_amount: Float!
    underlying_token_amount_usd: Float!
    earned: Float!
    earnedSnapshot: Float!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "Pool": Pool,
		"Strategy": Strategy,
		"VaultUser": VaultUser
  }
})
